const fs = require('fs')
const path = require('path')
const file = path.join(__dirname, 'src/components/home/raison-section.tsx')
let c = fs.readFileSync(file, 'utf8')

const r = (from, to) => { c = c.replace(from, to) }

// citoyen
r('title: "Le Portail Citoyen"', 'title: tx("Le Portail Citoyen", "The Citizen Portal")')
r('badge: "Citoyens de Terra Nova"', 'badge: tx("Citoyens de Terra Nova", "Citizens of Terra Nova")')
r("summary: \"Permettre aux habitants de s'informer, de signaler les incidents et de participer activement à la vie publique.\"", "summary: tx(\"Permettre aux habitants de s'informer, de signaler les incidents et de participer activement à la vie publique.\", \"Enabling residents to stay informed, report incidents and actively participate in public life.\")")
r('primaryCta: { label: "Accéder au Portail Citoyen"', 'primaryCta: { label: tx("Accéder au Portail Citoyen", "Access the Citizen Portal")')
r('name: "Tableau de Bord Citoyen"', 'name: tx("Tableau de Bord Citoyen", "Citizen Dashboard")')
r('desc: "Vue unifiée des démarches en cours, notifications prioritaires et métriques du secteur de résidence."', 'desc: tx("Vue unifiée des démarches en cours, notifications prioritaires et métriques du secteur de résidence.", "Unified view of ongoing procedures, priority notifications and residential sector metrics.")')
r('name: "Catalogue des Services Municipaux"', 'name: tx("Catalogue des Services Municipaux", "Municipal Services Catalogue")')
r('desc: "Consultation en temps réel des horaires, disponibilités et formulaires de démarche en ligne."', 'desc: tx("Consultation en temps réel des horaires, disponibilités et formulaires de démarche en ligne.", "Real-time access to schedules, availability and online procedure forms.")')
r("name: \"Signalement d'Incidents Géolocalisé\"", "name: tx(\"Signalement d'Incidents Géolocalisé\", \"Geolocated Incident Reporting\")")
r('desc: "Transmission immédiate des anomalies (infrastructures, énergie, réseaux) avec suivi de résolution."', 'desc: tx("Transmission immédiate des anomalies (infrastructures, énergie, réseaux) avec suivi de résolution.", "Immediate reporting of anomalies (infrastructure, energy, networks) with resolution tracking.")')
r('name: "Carte Interactive des 10 Secteurs"', 'name: tx("Carte Interactive des 10 Secteurs", "Interactive Map of the 10 Sectors")')
r("desc: \"Exploration des ruches hexagonales, transports autonomes et points d'intérêt municipaux.\"", "desc: tx(\"Exploration des ruches hexagonales, transports autonomes et points d'intérêt municipaux.\", \"Explore hexagonal hives, autonomous transport and municipal points of interest.\")")
r('name: "Assistant Virtuel IA"', 'name: tx("Assistant Virtuel IA", "AI Virtual Assistant")')
r('desc: "Guide conversationnel accessible par écrit et à la voix pour orienter chaque habitant sans délai."', 'desc: tx("Guide conversationnel accessible par écrit et à la voix pour orienter chaque habitant sans délai.", "Conversational guide accessible by text and voice to direct every resident without delay.")')
r('label: "Démarches 100% Dématérialisées"', 'label: tx("Démarches 100% Dématérialisées", "100% Digital Procedures")')
r('label: "Délai moyen de prise en charge"', 'label: tx("Délai moyen de prise en charge", "Average handling time")')
r('label: "Satisfaction citoyenne"', 'label: tx("Satisfaction citoyenne", "Citizen satisfaction")')

// agent
r('title: "L\'Espace des Agents Municipaux"', 'title: tx("L\'Espace des Agents Municipaux", "Municipal Agents Workspace")')
r('badge: "Forces d\'Intervention & Services"', 'badge: tx("Forces d\'Intervention & Services", "Intervention Forces & Services")')
r('summary: "Donner aux équipes locales les moyens de traiter efficacement les demandes et de maintenir l\'ordre dans une cité en pleine expansion."', 'summary: tx("Donner aux équipes locales les moyens de traiter efficacement les demandes et de maintenir l\'ordre dans une cité en pleine expansion.", "Giving local teams the tools to efficiently handle requests and maintain order in a rapidly expanding city.")')
r('primaryCta: { label: "Console d\'Intervention"', 'primaryCta: { label: tx("Console d\'Intervention", "Intervention Console")')
r('name: "Centre de Dispatching & Interventions"', 'name: tx("Centre de Dispatching & Interventions", "Dispatching & Intervention Centre")')
r('desc: "Attribution intelligente des missions terrain selon la proximité sectorielle et l\'urgence."', 'desc: tx("Attribution intelligente des missions terrain selon la proximité sectorielle et l\'urgence.", "Smart assignment of field missions based on sector proximity and urgency.")')
r('name: "Traitement Rapide des Demandes"', 'name: tx("Traitement Rapide des Demandes", "Fast Request Processing")')
r('desc: "Interface optimisée de validation des requêtes citoyennes avec respect strict des délais légaux."', 'desc: tx("Interface optimisée de validation des requêtes citoyennes avec respect strict des délais légaux.", "Optimised interface for validating citizen requests with strict compliance to legal deadlines.")')
r('name: "Supervision des Signalements"', 'name: tx("Supervision des Signalements", "Report Supervision")')
r('desc: "Suivi des réparations techniques, vérification des alertes capteurs et clôture avec compte-rendu."', 'desc: tx("Suivi des réparations techniques, vérification des alertes capteurs et clôture avec compte-rendu.", "Tracking technical repairs, verifying sensor alerts and closing with a report.")')
r('name: "Coordination d\'Équipe & Sync"', 'name: tx("Coordination d\'Équipe & Sync", "Team Coordination & Sync")')
r('desc: "Télémétrie opérationnelle entre les brigades mobiles et le centre de commandement urbain."', 'desc: tx("Télémétrie opérationnelle entre les brigades mobiles et le centre de commandement urbain.", "Operational telemetry between mobile units and the urban command centre.")')
r('label: "Taux de résolution dans les délais"', 'label: tx("Taux de résolution dans les délais", "On-time resolution rate")')
r('label: "Secteurs couverts en temps réel"', 'label: tx("Secteurs couverts en temps réel", "Sectors covered in real time")')
r('label: "Temps moyen d\'intervention"', 'label: tx("Temps moyen d\'intervention", "Average intervention time")')

// admin
r('title: "La Console d\'Administration"', 'title: tx("La Console d\'Administration", "The Administration Console")')
r('badge: "Gouvernance & Haute Supervision"', 'badge: tx("Gouvernance & Haute Supervision", "Governance & High Supervision")')
r('summary: "Centraliser la gouvernance, valider les données issues des capteurs et garantir la transparence grâce à des journaux d\'audit."', 'summary: tx("Centraliser la gouvernance, valider les données issues des capteurs et garantir la transparence grâce à des journaux d\'audit.", "Centralising governance, validating sensor data and ensuring transparency through audit logs.")')
r('primaryCta: { label: "Supervision Gouvernance"', 'primaryCta: { label: tx("Supervision Gouvernance", "Governance Supervision")')
r('name: "Supervision Globale de la Ruche"', 'name: tx("Supervision Globale de la Ruche", "Global Hive Supervision")')
r('desc: "Indicateurs macroscopiques : flux d\'énergie, circulation, santé des réseaux et démographie."', 'desc: tx("Indicateurs macroscopiques : flux d\'énergie, circulation, santé des réseaux et démographie.", "Macroscopic indicators: energy flows, traffic, network health and demographics.")')
r('name: "Journaux d\'Audit & Traçabilité Cryptographique"', 'name: tx("Journaux d\'Audit & Traçabilité Cryptographique", "Audit Logs & Cryptographic Traceability")')
r('desc: "Registre inviolable de chaque décision publique garantissant une transparence totale et vérifiable."', 'desc: tx("Registre inviolable de chaque décision publique garantissant une transparence totale et vérifiable.", "Tamper-proof record of every public decision ensuring total and verifiable transparency.")')
r('name: "Validation des Données Capteurs & IA"', 'name: tx("Validation des Données Capteurs & IA", "Sensor & AI Data Validation")')
r('desc: "Gouvernance des alertes automatisées, réglage des seuils atmosphériques et modération intelligente."', 'desc: tx("Gouvernance des alertes automatisées, réglage des seuils atmosphériques et modération intelligente.", "Governance of automated alerts, atmospheric threshold tuning and intelligent moderation.")')
r('name: "Éditeur Territorial des 10 Secteurs"', 'name: tx("Éditeur Territorial des 10 Secteurs", "Territorial Editor of the 10 Sectors")')
r('desc: "Configuration cartographique des infrastructures modulaires, des zones protégées et des accès."', 'desc: tx("Configuration cartographique des infrastructures modulaires, des zones protégées et des accès.", "Cartographic configuration of modular infrastructure, protected zones and access points.")')
r('label: "Intégrité des données d\'audit"', 'label: tx("Intégrité des données d\'audit", "Audit data integrity")')
r('label: "Capteurs IoT interconnectés"', 'label: tx("Capteurs IoT interconnectés", "Interconnected IoT sensors")')
r('label: "Transparence décisionnelle", val: "Totale"', 'label: tx("Transparence décisionnelle", "Decision transparency"), val: tx("Totale", "Total")')

// Section headers JSX
r('Genèse & Vision Fondatrice', 'tx("Genèse & Vision Fondatrice", "Genesis & Founding Vision")')
r('Pourquoi <span', 'tx("Pourquoi", "Why") + " "} <span')
r('>Nova Terra</span> ?', '>Nova Terra</span> ?')
r("Au départ, les colons utilisaient des systèmes fragmentés pour gérer les ressources, les communications et la sécurité.\n              Mais face à la complexité croissante, les fondateurs décidèrent de créer une <strong className=\"text-cyan-300 font-semibold\">plateforme unique</strong> : <span className=\"text-white font-semibold\">Nova Terra</span>.", "{tx(\"Au départ, les colons utilisaient des systèmes fragmentés pour gérer les ressources, les communications et la sécurité. Mais face à la complexité croissante, les fondateurs décidèrent de créer une\", \"Initially, colonists used fragmented systems to manage resources, communications and security. Faced with growing complexity, the founders decided to create a\")} <strong className=\"text-cyan-300 font-semibold\">{tx(\"plateforme unique\", \"single platform\")}</strong> : <span className=\"text-white font-semibold\">Nova Terra</span>.")
r('La Vision Fondatrice', 'tx("La Vision Fondatrice", "The Founding Vision")')
r("« Leur vision était claire : Nova Terra devait devenir <span className=\"text-transparent bg-clip-text bg-linear-to-r from-cyan-300 via-sky-200 to-indigo-200 font-bold underline decoration-cyan-400/40 underline-offset-8\">le laboratoire vivant d'une société idéale</span>. »", "{tx(\"« Leur vision était claire : Nova Terra devait devenir\", '\"Their vision was clear: Nova Terra was to become')} <span className=\"text-transparent bg-clip-text bg-linear-to-r from-cyan-300 via-sky-200 to-indigo-200 font-bold underline decoration-cyan-400/40 underline-offset-8\">{tx(\"le laboratoire vivant d'une société idéale\", \"the living laboratory of an ideal society\")}</span>{tx('. »', '."')}")
r('Portés par une mission sans compromis', 'tx("Portés par une mission sans compromis", "Driven by an uncompromising mission")')
r("Trois Piliers d'Équilibre Planétaire", 'tx("Trois Piliers d\'Équilibre Planétaire", "Three Pillars of Planetary Balance")')
r('Créer une civilisation durable', 'tx("Créer une civilisation durable", "Building a sustainable civilisation")')
r("Affranchie des crises écologiques et sociales qui avaient marqué la Terre, grâce à un cycle complet de recyclage et une autonomie énergétique intégrale.", "tx(\"Affranchie des crises écologiques et sociales qui avaient marqué la Terre, grâce à un cycle complet de recyclage et une autonomie énergétique intégrale.\", \"Free from the ecological and social crises that marked Earth, thanks to a complete recycling cycle and full energy autonomy.\")")
r('Empreinte Zéro • Écosystème Préservé', 'tx("Empreinte Zéro • Écosystème Préservé", "Zero Footprint • Preserved Ecosystem")')
r('Expérimenter un nouveau modèle de gouvernance', 'tx("Expérimenter un nouveau modèle de gouvernance", "Experimenting with a new governance model")')
r("Où la technologie ne serait pas un outil de contrôle mais un vecteur de transparence et de participation citoyenne active et directe.", "tx(\"Où la technologie ne serait pas un outil de contrôle mais un vecteur de transparence et de participation citoyenne active et directe.\", \"Where technology would not be a tool of control but a vector of transparency and active, direct citizen participation.\")")
r('Démocratie Numérique Ouverte', 'tx("Démocratie Numérique Ouverte", "Open Digital Democracy")')
r("Préserver l'équilibre nature & urbanisation", "tx(\"Préserver l'équilibre nature & urbanisation\", \"Preserving the nature & urbanisation balance\")")
r("En intégrant l'intelligence artificielle dès la conception des infrastructures, afin d'optimiser en permanence les ressources sans dénaturer la faune et la flore locales.", "tx(\"En intégrant l'intelligence artificielle dès la conception des infrastructures, afin d'optimiser en permanence les ressources sans dénaturer la faune et la flore locales.\", \"By integrating artificial intelligence from the design of infrastructure, to permanently optimise resources without harming local flora and fauna.\")")
r('Bio-Ingénierie & IA Prédictive', 'tx("Bio-Ingénierie & IA Prédictive", "Bio-Engineering & Predictive AI")')

// Section 2 headers
r('Architecture & Écrans Connectés', 'tx("Architecture & Écrans Connectés", "Architecture & Connected Screens")')
r('Une Plateforme, <span', 'tx("Une Plateforme,", "One Platform,") + " "} <span')
r('>Trois Espaces Dédiés</span>', '>{tx("Trois Espaces Dédiés", "Three Dedicated Spaces")}</span>')
r("Chaque strate de la société de Terra Nova dispose d'outils sur mesure, directement connectés au système nerveux central.", "tx(\"Chaque strate de la société de Terra Nova dispose d'outils sur mesure, directement connectés au système nerveux central.\", \"Every layer of Terra Nova society has tailored tools, directly connected to the central nervous system.\")")
r('1. Portail Citoyen', 'tx("1. Portail Citoyen", "1. Citizen Portal")')
r('2. Agents Municipaux', 'tx("2. Agents Municipaux", "2. Municipal Agents")')
r("3. Console d'Administration", "tx(\"3. Console d'Administration\", \"3. Administration Console\")")
r("Ouvrir l'écran", "tx(\"Ouvrir l'écran\", \"Open screen\")")

// Section 3
r('Transformation Sociétale', 'tx("Transformation Sociétale", "Societal Transformation")')
r("Bien Plus Qu'une Application", "tx(\"Bien Plus Qu'une Application\", \"More Than an Application\")")
r("Au fil des décennies, Nova Terra s'est métamorphosée en l'ossature vivante et permanente de toute la cité.", "tx(\"Au fil des décennies, Nova Terra s'est métamorphosée en l'ossature vivante et permanente de toute la cité.\", \"Over the decades, Nova Terra has transformed into the living, permanent backbone of the entire city.\")")
r('Un système nerveux digital', 'tx("Un système nerveux digital", "A digital nervous system")')
r("Reliant chaque citoyen, chaque infrastructure et chaque décision en un maillage fluide, continu et instantané.", "tx(\"Reliant chaque citoyen, chaque infrastructure et chaque décision en un maillage fluide, continu et instantané.\", \"Connecting every citizen, every piece of infrastructure and every decision in a fluid, continuous and instant network.\")")
r('Un outil de confiance', 'tx("Un outil de confiance", "A trust tool")')
r("Qui assure la sécurité, la fluidité et la transparence dans une société en constante mutation et en pleine croissance.", "tx(\"Qui assure la sécurité, la fluidité et la transparence dans une société en constante mutation et en pleine croissance.\", \"Ensuring security, fluidity and transparency in a constantly evolving and rapidly growing society.\")")
r('Une mémoire collective', 'tx("Une mémoire collective", "A collective memory")')
r("Capable de préserver l'histoire de la colonie tout en anticipant ses besoins futurs grâce aux modèles prédictifs continus.", "tx(\"Capable de préserver l'histoire de la colonie tout en anticipant ses besoins futurs grâce aux modèles prédictifs continus.\", \"Capable of preserving the colony's history while anticipating its future needs through continuous predictive models.\")")

// Section 4
r('Progrès Majeurs & Réalisations', 'tx("Progrès Majeurs & Réalisations", "Major Progress & Achievements")')
r('Les Avancements de <span', 'tx("Les Avancements de", "The Advances of") + " "} <span')
r('>Nova Terra</span>\n            </h2>\n\n            <p className="mt-4 text-slate-300 font-light text-base sm:text-lg">\n              Six innovations systémiques qui ont permis à la cité de devenir un modèle d\'harmonie urbaine et écologique.', '>{tx("Nova Terra","Nova Terra")}</span>\n            </h2>\n\n            <p className="mt-4 text-slate-300 font-light text-base sm:text-lg">\n              {tx("Six innovations systémiques qui ont permis à la cité de devenir un modèle d\'harmonie urbaine et écologique.", "Six systemic innovations that enabled the city to become a model of urban and ecological harmony.")}')
r('Centralisation numérique', 'tx("Centralisation numérique", "Digital centralisation")')
r("Nova Terra est devenue le cœur digital de la cité, reliant citoyens, agents et administrateurs sur une seule infrastructure unifiée.", "tx(\"Nova Terra est devenue le cœur digital de la cité, reliant citoyens, agents et administrateurs sur une seule infrastructure unifiée.\", \"Nova Terra has become the digital heart of the city, connecting citizens, agents and administrators on a single unified infrastructure.\")")
r('Cœur Digital Unifié', 'tx("Cœur Digital Unifié", "Unified Digital Core")')
r("Voir l'espace", "tx(\"Voir l'espace\", \"View workspace\")")
r('Infrastructure intelligente', 'tx("Infrastructure intelligente", "Smart infrastructure")')
r("Les 10 secteurs hexagonaux sont interconnectés par des réseaux autonomes de transport, d'énergie et de télécommunication quantique.", "tx(\"Les 10 secteurs hexagonaux sont interconnectés par des réseaux autonomes de transport, d'énergie et de télécommunication quantique.\", \"The 10 hexagonal sectors are interconnected by autonomous transport, energy and quantum telecommunications networks.\")")
r('10 Secteurs Interconnectés', 'tx("10 Secteurs Interconnectés", "10 Interconnected Sectors")')
r('Carte interactive', 'tx("Carte interactive", "Interactive map")')
r('Participation citoyenne', 'tx("Participation citoyenne", "Citizen participation")')
r("Grâce au portail, les habitants peuvent signaler incidents, consulter les services et participer activement à la gouvernance de leur ruche.", "tx(\"Grâce au portail, les habitants peuvent signaler incidents, consulter les services et participer activement à la gouvernance de leur ruche.\", \"Through the portal, residents can report incidents, consult services and actively participate in the governance of their hive.\")")
r('Démocratie Active', 'tx("Démocratie Active", "Active Democracy")')
r('Consulter les signalements', 'tx("Consulter les signalements", "View reports")')
r('Efficacité administrative', 'tx("Efficacité administrative", "Administrative efficiency")')
r("Les agents municipaux disposent d'outils avancés pour traiter rapidement les demandes et respecter scrupuleusement les délais légaux.", "tx(\"Les agents municipaux disposent d'outils avancés pour traiter rapidement les demandes et respecter scrupuleusement les délais légaux.\", \"Municipal agents have advanced tools to quickly process requests and scrupulously meet legal deadlines.\")")
r('Délais & SLA Optimisés', 'tx("Délais & SLA Optimisés", "Optimised Deadlines & SLAs")')
r('Espace Agent', 'tx("Espace Agent", "Agent Workspace")')
r('Transparence et sécurité', 'tx("Transparence et sécurité", "Transparency and security")')
r("La console d'administration assure la traçabilité et la validation des données issues des capteurs et de l'IA via des registres d'audit infalsifiables.", "tx(\"La console d'administration assure la traçabilité et la validation des données issues des capteurs et de l'IA via des registres d'audit infalsifiables.\", \"The administration console ensures traceability and validation of sensor and AI data through tamper-proof audit registers.\")")
r('Registres Cryptographiques', 'tx("Registres Cryptographiques", "Cryptographic Registers")')
r("Consulter l'audit", "tx(\"Consulter l'audit\", \"View audit\")")
r('Évolution durable', 'tx("Évolution durable", "Sustainable evolution")')
r("Intégration progressive de l'IA pour anticiper les besoins collectifs, réguler l'énergie solaire et optimiser les ressources de la colonie.", "tx(\"Intégration progressive de l'IA pour anticiper les besoins collectifs, réguler l'énergie solaire et optimiser les ressources de la colonie.\", \"Progressive AI integration to anticipate collective needs, regulate solar energy and optimise colony resources.\")")
r('IA Écologique & Prédictive', 'tx("IA Écologique & Prédictive", "Ecological & Predictive AI")')
r('Assistant IA', 'tx("Assistant IA", "AI Assistant")')

// Section 5 CTA
r("Prêt à explorer Terra Nova ?", "tx(\"Prêt à explorer Terra Nova ?\", \"Ready to explore Terra Nova?\")")
r('Embarquez au cœur du nouveau monde', 'tx("Embarquez au cœur du nouveau monde", "Embark into the heart of the new world")')
r("Que vous soyez citoyen, visiteur ou agent de la colonie, accédez immédiatement à l'ensemble des services intelligents de Nova Terra.", "tx(\"Que vous soyez citoyen, visiteur ou agent de la colonie, accédez immédiatement à l'ensemble des services intelligents de Nova Terra.\", \"Whether you are a citizen, visitor or colony agent, immediately access all of Nova Terra's intelligent services.\")")
r('Rejoindre la Cité', 'tx("Rejoindre la Cité", "Join the City")')
r('Explorer la Carte des 10 Secteurs', 'tx("Explorer la Carte des 10 Secteurs", "Explore the Map of 10 Sectors")')
r('Consulter les Services', 'tx("Consulter les Services", "Browse Services")')

// Footer
r('Plateforme centrale de gestion intelligente et participative des 10 secteurs hexagonaux de la planète Terra Nova.', 'tx("Plateforme centrale de gestion intelligente et participative des 10 secteurs hexagonaux de la planète Terra Nova.", "Central platform for intelligent and participatory management of the 10 hexagonal sectors of planet Terra Nova.")')
r('10/10 Secteurs Opérationnels', 'tx("10/10 Secteurs Opérationnels", "10/10 Sectors Operational")')
r('>Navigation<', '>{tx("Navigation","Navigation")}<')
r('>Historique 2087<', '>{tx("Historique 2087","History 2087")}<')
r('>Vision & Missions<', '>{tx("Vision & Missions","Vision & Missions")}<')
r('>Les 3 Espaces<', '>{tx("Les 3 Espaces","The 3 Spaces")}<')
r('>Avancements<', '>{tx("Avancements","Advances")}<')
r('>Écrans Connectés<', '>{tx("Écrans Connectés","Connected Screens")}<')
r('>Carte Hexagonale<', '>{tx("Carte Hexagonale","Hexagonal Map")}<')
r('>Catalogue des Services<', '>{tx("Catalogue des Services","Services Catalogue")}<')
r(">Protocoles d'Alerte<", ">{tx(\"Protocoles d'Alerte\",\"Alert Protocols\")}<")
r('>Espace Citoyen<', '>{tx("Espace Citoyen","Citizen Space")}<')
r('>Espace Agent Municipal<', '>{tx("Espace Agent Municipal","Municipal Agent Space")}<')
r('>Console Administrateur<', '>{tx("Console Administrateur","Administrator Console")}<')
r('© 2087-2126 Terra Nova Metropolitan Governance. Tous droits réservés.', '{tx("© 2087-2126 Terra Nova Metropolitan Governance. Tous droits réservés.", "© 2087-2126 Terra Nova Metropolitan Governance. All rights reserved.")}')
r('>Conditions<', '>{tx("Conditions","Terms")}<')
r('>Confidentialité<', '>{tx("Confidentialité","Privacy")}<')
r('>Équipe Fondatrice<', '>{tx("Équipe Fondatrice","Founding Team")}<')
r('>Guide Urbain<', '>{tx("Guide Urbain","Urban Guide")}<')

fs.writeFileSync(file, c, 'utf8')
console.log('done')
