import type { AppUser } from "@/features/auth/auth-context"
import type { Item } from "@/features/items/items-api"
import type { Locale } from "@/lib/locale"

interface ReportStrings {
  title: string
  generatedOn: string
  generatedBy: string
  sections: { profile: string; activity: string; notes: string }
  fields: {
    name: string; email: string; role: string; backend: string
    total: string; publicNotes: string; privateNotes: string
    noNotes: string; admin: string; member: string; supabase: string; local: string
    public: string; private: string
  }
}

const STRINGS: Record<"fr" | "en", ReportStrings> = {
  fr: {
    title: "Rapport synthétique d'activité",
    generatedOn: "Généré le",
    generatedBy: "Généré par",
    sections: { profile: "Profil", activity: "Activité", notes: "Notes" },
    fields: {
      name: "Nom", email: "E-mail", role: "Rôle", backend: "Connexion",
      total: "Total notes", publicNotes: "Notes publiques", privateNotes: "Notes privées",
      noNotes: "Aucune note.", admin: "Administrateur", member: "Membre",
      supabase: "Supabase", local: "Démo locale", public: "publique", private: "privée",
    },
  },
  en: {
    title: "Synthetic Activity Report",
    generatedOn: "Generated on",
    generatedBy: "Generated by",
    sections: { profile: "Profile", activity: "Activity", notes: "Notes" },
    fields: {
      name: "Name", email: "Email", role: "Role", backend: "Connection",
      total: "Total notes", publicNotes: "Public notes", privateNotes: "Private notes",
      noNotes: "No notes.", admin: "Administrator", member: "Member",
      supabase: "Supabase", local: "Local demo", public: "public", private: "private",
    },
  },
}

function getStrings(locale: Locale): ReportStrings {
  return locale === "fr" ? STRINGS.fr : STRINGS.en
}

function block(title: string, lines: string[]): string {
  const bar = "─".repeat(42)
  return ["\n" + bar, "  " + title.toUpperCase(), bar, ...lines].join("\n")
}

export function buildReport(
  user: AppUser,
  items: Item[],
  locale: Locale,
  backend: "supabase" | "local",
  tag: string,
): string {
  const s = getStrings(locale)
  const now = new Intl.DateTimeFormat(tag, { dateStyle: "full", timeStyle: "short" }).format(new Date())
  const userItems = items.filter((i) => i.user_id === user.id)
  const publicCount = userItems.filter((i) => i.is_public).length

  const noteLines =
    userItems.length === 0
      ? ["  " + s.fields.noNotes]
      : userItems.map((i) => {
          const date = new Intl.DateTimeFormat(tag, { dateStyle: "short" }).format(new Date(i.created_at))
          const vis = i.is_public ? s.fields.public : s.fields.private
          return `  • [${date}] ${i.title} (${vis})`
        })

  return [
    "═".repeat(44),
    "  " + s.title.toUpperCase(),
    "═".repeat(44),
    "  " + s.generatedOn + ": " + now,
    "  " + s.generatedBy + ": " + user.displayName,
    block(s.sections.profile, [
      `  ${s.fields.name}: ${user.displayName}`,
      `  ${s.fields.email}: ${user.email}`,
      `  ${s.fields.role}: ${user.isAdmin ? s.fields.admin : s.fields.member}`,
      `  ${s.fields.backend}: ${backend === "supabase" ? s.fields.supabase : s.fields.local}`,
    ]),
    block(s.sections.activity, [
      `  ${s.fields.total}: ${userItems.length}`,
      `  ${s.fields.publicNotes}: ${publicCount}`,
      `  ${s.fields.privateNotes}: ${userItems.length - publicCount}`,
    ]),
    block(s.sections.notes, noteLines),
    "\n" + "═".repeat(44) + "\n",
  ].join("\n")
}

export function downloadReport(content: string, locale: Locale): void {
  const filename = locale === "fr" ? "rapport-activite.txt" : "activity-report.txt"
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
